import random
import string
from datetime import timedelta, datetime
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Level(models.Model):
    name = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return f"Level {self.name}"


class Semester(models.Model):
    name = models.CharField(max_length=50)
    year = models.IntegerField()
    start_date = models.DateField()
    end_date = models.DateField()
    is_active = models.BooleanField(default=False)
    is_archived = models.BooleanField(default=False)

    def __str__(self):
        status = " (Archived)" if self.is_archived else " (Active)" if self.is_active else ""
        return f"{self.name} {self.year}{status}"


class Course(models.Model):
    code = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=100)
    level = models.ForeignKey(Level, on_delete=models.CASCADE)
    semester = models.ForeignKey(Semester, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.code} - {self.name}"


class ClassSession(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    date = models.DateField()
    start_time = models.TimeField(default='07:30', help_text="Class start time (e.g., 07:30)")
    end_time = models.TimeField(default='09:20', help_text="Class end time (e.g., 09:20)")
    topic = models.CharField(max_length=200)
    lecturer = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.course} on {self.date} ({self.start_time} - {self.end_time})"
    
    def is_active_now(self):
        """Check if class is currently active (within time window)"""
        now = timezone.now()
        today = now.date()
        current_time = now.time()
        
        if self.date == today:
            return self.start_time <= current_time <= self.end_time
        return False


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    level = models.ForeignKey(Level, on_delete=models.SET_NULL, null=True, blank=True)
    student_id_number = models.CharField(max_length=50, unique=True, blank=True, null=True)
    student_email = models.EmailField(blank=True, null=True)
    registered_courses = models.ManyToManyField(Course, blank=True, related_name='registered_students')
    
    # Email Verification Fields
    email_verified = models.BooleanField(default=False)
    email_verification_token = models.CharField(max_length=100, blank=True, null=True)
    verification_sent_at = models.DateTimeField(blank=True, null=True)

    must_change_password = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.user.username} - Level {self.level}"


class TAProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    assigned_levels = models.ManyToManyField(Level, blank=True, help_text="Which levels this TA handles")
    assigned_courses = models.ManyToManyField(Course, blank=True, help_text="Specific courses this TA handles")
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    
    # TA Approval Fields
    is_approved = models.BooleanField(default=False)
    approved_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='approved_tas')
    approved_at = models.DateTimeField(blank=True, null=True)
    approval_notes = models.TextField(blank=True, null=True)

    def __str__(self):
        levels = ', '.join([l.name for l in self.assigned_levels.all()])
        status = "✓ Approved" if self.is_approved else "⏳ Pending Approval"
        return f"TA: {self.user.username} - Levels: {levels} - {status}"


class TACode(models.Model):
    """Code generated by TA for a specific student and session"""
    code = models.CharField(max_length=5)
    student = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ta_codes')
    class_session = models.ForeignKey(ClassSession, on_delete=models.CASCADE)
    ta = models.ForeignKey(User, on_delete=models.CASCADE, related_name='generated_codes')
    generated_at = models.DateTimeField(auto_now_add=True)
    used_at = models.DateTimeField(null=True, blank=True)
    is_used = models.BooleanField(default=False)
    is_distributed = models.BooleanField(default=False)
    distributed_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        unique_together = ['code', 'class_session']

    def __str__(self):
        status = "Used" if self.is_used else "Pending"
        return f"Code {self.code} for {self.student.username} - {status}"


class AttendanceCode(models.Model):
    code_string = models.CharField(max_length=20, unique=True, blank=True)
    student = models.ForeignKey(User, on_delete=models.CASCADE, related_name='codes')
    class_session = models.ForeignKey(ClassSession, on_delete=models.CASCADE)
    generated_at = models.DateTimeField(default=timezone.now)
    expires_at = models.DateTimeField(null=True, blank=True)
    used_at = models.DateTimeField(null=True, blank=True)
    is_valid = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.code_string:
            self.code_string = ''.join(random.choices(
                string.ascii_uppercase + string.digits, k=8
            ))
        
        if not self.expires_at:
            session_date = self.class_session.date
            expiry_datetime = datetime.combine(session_date, datetime.max.time()) + timedelta(days=7)
            self.expires_at = timezone.make_aware(expiry_datetime)
        
        super().save(*args, **kwargs)

    def can_use(self):
        if self.used_at:
            return False, "Code already used"
        if self.is_expired():
            return False, "Code has expired"
        if not self.is_valid:
            return False, "Code is invalid"
        return True, "OK"

    def is_expired(self):
        return timezone.now() > self.expires_at

    def __str__(self):
        return f"{self.code_string} for {self.student.username}"


class AttendanceRecord(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE, related_name='attendance')
    class_session = models.ForeignKey(ClassSession, on_delete=models.CASCADE)
    code = models.OneToOneField(AttendanceCode, on_delete=models.CASCADE)
    submitted_at = models.DateTimeField(auto_now_add=True)
    ip_address = models.GenericIPAddressField(null=True, blank=True)
    user_agent = models.TextField(blank=True, null=True)
    status = models.CharField(max_length=20, default='on_time')

    def __str__(self):
        return f"{self.student.username} attended {self.class_session}"


class SupportTicket(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('in_progress', 'In Progress'),
        ('resolved', 'Resolved'),
        ('closed', 'Closed'),
    ]
    
    student = models.ForeignKey(User, on_delete=models.CASCADE, related_name='support_tickets')
    subject = models.CharField(max_length=200)
    message = models.TextField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    admin_response = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.subject} - {self.student.username}"


class CodeMisuseAlert(models.Model):
    code = models.ForeignKey(AttendanceCode, on_delete=models.SET_NULL, null=True, blank=True)
    attempted_by = models.ForeignKey(User, on_delete=models.CASCADE)
    attempted_at = models.DateTimeField(auto_now_add=True)
    reason = models.CharField(max_length=200)
    is_resolved = models.BooleanField(default=False)

    def __str__(self):
        return f"Misuse alert: {self.code.code_string} by {self.attempted_by.username}"