"""
Django settings for swasa_attendance project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path

import dj_database_url
from decouple import config, Csv

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY', default='')
if not SECRET_KEY:
    # No key in environment. Allow local dev commands with a throwaway key,
    # but never let production run without a real one.
    _is_dev_command = any(a in sys.argv for a in ['runserver', 'test', 'shell', 'migrate', 'makemigrations'])
    if _is_dev_command:
        import secrets
        SECRET_KEY = secrets.token_urlsafe(50)  # ephemeral, regenerated each run
    else:
        raise RuntimeError("DJANGO_SECRET_KEY environment variable is not set.")

DEBUG = config('DJANGO_DEBUG', default='True', cast=bool)

# ALLOWED_HOSTS
#
# In development we allow the local + tunneling conveniences. In production we
# only trust what's explicitly configured via the ALLOWED_HOSTS env var (comma
# separated), so the app isn't reachable under the whole shared .pythonanywhere
# .com / .ngrok space. If nothing is configured we fall back to
# .pythonanywhere.com so a missing var doesn't 400 everything — but you SHOULD
# pin your exact host in .env for production.
_extra_hosts = list(config('ALLOWED_HOSTS', default='', cast=Csv()))

if DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.ngrok-free.dev', '.pythonanywhere.com'] + _extra_hosts
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1'] + _extra_hosts
    if not _extra_hosts:
        ALLOWED_HOSTS.append('.pythonanywhere.com')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'attendance',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'attendance.middleware.JWTAuthMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'attendance.middleware.ForcePasswordChangeMiddleware',
]

# JWT Settings (cookie-based sessions — existing system)
JWT_SECRET_KEY = config('JWT_SECRET_KEY', default=SECRET_KEY)

# Public URL of this site (used for magic-link emails)
SITE_URL = config('SITE_URL', default='https://ebenezer.pythonanywhere.com')

# djangorestframework-simplejwt (API tokens)
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': JWT_SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Rate limiting. The unauthenticated OTP endpoints are the main brute-force
    # surface, so they get their own tighter scopes (applied per-view).
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/hour',
        'user': '1000/hour',
        'otp_request': '10/hour',   # requesting an OTP be emailed
        'otp_verify': '15/hour',    # submitting an OTP guess
    },
}

ROOT_URLCONF = 'swasa_attendance.urls'

_TEMPLATE_CONTEXT_PROCESSORS = [
    'django.template.context_processors.debug',
    'django.template.context_processors.request',
    'django.contrib.auth.context_processors.auth',
    'django.contrib.messages.context_processors.messages',
    'attendance.context_processors.notifications',
]

_BASE_LOADERS = [
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'OPTIONS': {
            'context_processors': _TEMPLATE_CONTEXT_PROCESSORS,
            'loaders': _BASE_LOADERS if DEBUG else [
                ('django.template.loaders.cached.Loader', _BASE_LOADERS)
            ],
        },
    },
]

WSGI_APPLICATION = 'swasa_attendance.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=0)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Cache
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'swasa-cache',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    # NumericPasswordValidator is commented out to allow Student ID as password
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Accra'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'assets'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Media files (user uploaded files)
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Login/Logout URLs
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'attendance:dashboard'
LOGOUT_REDIRECT_URL = 'login'

# CSRF trusted origins.
#
# Dev keeps the http+https tunnel wildcards for convenience. Production trusts
# HTTPS only, derived from the configured hosts (or an explicit
# CSRF_TRUSTED_ORIGINS env var) — no plaintext-http origins, no ngrok.
if DEBUG:
    CSRF_TRUSTED_ORIGINS = [
        'https://*.pythonanywhere.com',
        'http://*.pythonanywhere.com',
        'https://*.ngrok-free.dev',
        'http://*.ngrok-free.dev',
    ]
else:
    _csrf_env = list(config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv()))
    if _csrf_env:
        CSRF_TRUSTED_ORIGINS = _csrf_env
    else:
        CSRF_TRUSTED_ORIGINS = [
            (f"https://*{h}" if h.startswith('.') else f"https://{h}")
            for h in (_extra_hosts or ['.pythonanywhere.com'])
        ]

# Cookie / transport security.
#
# These default to `not DEBUG`, but are ALSO independently overridable via the
# SECURE_COOKIES env var so a production box can force secure cookies on even if
# DEBUG were ever misconfigured. The whole transport posture no longer hinges on
# a single flag. In production set SECURE_COOKIES=True explicitly.
SECURE_COOKIES = config('SECURE_COOKIES', default=not DEBUG, cast=bool)

CSRF_COOKIE_SECURE = SECURE_COOKIES
SESSION_COOKIE_SECURE = SECURE_COOKIES
# Read by the custom JWT-cookie login views to set the `secure` flag on the
# access/refresh cookies (keeps them aligned with the session/CSRF cookies).
JWT_COOKIE_SECURE = SECURE_COOKIES

# Fail fast on an insecure production configuration: if DEBUG is off, refuse to
# boot a real server with insecure cookies. Dev commands are exempt so local
# work over plain HTTP still runs.
if not DEBUG and not SECURE_COOKIES:
    _is_dev_command = any(
        a in sys.argv
        for a in ['runserver', 'test', 'shell', 'migrate', 'makemigrations', 'collectstatic', 'check']
    )
    if not _is_dev_command:
        raise RuntimeError(
            "Insecure configuration: DEBUG=False but SECURE_COOKIES=False. "
            "Set SECURE_COOKIES=True (or DJANGO_DEBUG=True for local dev)."
        )

# ========== EMAIL CONFIGURATION ==========
# Credentials are read from .env via python-decouple.
# When EMAIL_HOST_USER / EMAIL_HOST_PASSWORD are present, Gmail SMTP is used.
# Leave them blank in .env to fall back to the console backend (dev/testing).

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = 'SWASA <jifunzekiswahilisasa@gmail.com>'

# Fall back to console backend when credentials are absent (avoids SMTP errors in dev)
if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Email timeout (seconds)
EMAIL_TIMEOUT = 30

# Password reset email subject template
PASSWORD_RESET_SUBJECT_TEMPLATE = 'registration/password_reset_subject.txt'

# Security settings — always on
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Security settings — production only (behind PythonAnywhere / Render HTTPS proxy)
if not DEBUG:
    # Tell Django it's behind an HTTPS reverse proxy — prevents redirect loops
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Do NOT set SECURE_SSL_REDIRECT on PythonAnywhere — the proxy handles it
    # SECURE_SSL_REDIRECT = True  ← causes redirect loops on PA
    SECURE_HSTS_SECONDS = 31536000      # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = False         # Keep False until fully verified on HSTS preload list