# Generated by Django 6.0.5 on 2026-05-27 02:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20260523_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancecode',
            name='code_string',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='attendancecode',
            name='generated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
