# Generated by Django 6.0.5 on 2026-05-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendancecode_code_string_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
