# Generated by Django 6.0.5 on 2026-05-28 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendancecode_is_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(default='on_time', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classsession',
            name='end_time',
            field=models.TimeField(default='09:20', help_text='Class end time (e.g., 09:20)'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='start_time',
            field=models.TimeField(default='07:30', help_text='Class start time (e.g., 07:30)'),
        ),
        migrations.CreateModel(
            name='TAProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_courses', models.ManyToManyField(blank=True, help_text='Specific courses this TA handles', to='attendance.course')),
                ('assigned_levels', models.ManyToManyField(blank=True, help_text='Which levels this TA handles', to='attendance.level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TACode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('is_distributed', models.BooleanField(default=False)),
                ('distributed_at', models.DateTimeField(blank=True, null=True)),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.classsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_codes', to=settings.AUTH_USER_MODEL)),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('code', 'class_session')},
            },
        ),
    ]
