# Generated by Django 6.0.5 on 2026-06-06 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_taprofile_approval_notes_taprofile_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codemisusealert',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.attendancecode'),
        ),
    ]
