# Generated by Django 6.0.5 on 2026-06-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_userprofile_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancecode',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
