# Generated by Django 6.0.5 on 2026-06-13 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_swasaevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('deregistered_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to='attendance.course')),
                ('deregistered_by', models.ForeignKey(blank=True, help_text='User (student, TA, or admin) who performed the deregistration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deregistrations', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to='attendance.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'course')},
            },
        ),
    ]
