# Generated by Django 6.0.5 on 2026-08-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_use_courseregistration_through'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tacode',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
