# Generated by Django 6.0.5 on 2026-08-21 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_create_cache_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='swasaevent',
            name='target_levels',
            field=models.ManyToManyField(blank=True, related_name='events', to='attendance.level'),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='attendance.swasaevent'),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='link',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
